# Generated by Django 6.1 on 2026-09-13 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='The raw natural language query provided by the client.')),
                ('ai_proposed_sql', models.TextField(blank=True, help_text='The raw, untrusted SQL string generated directly by the LLM.', null=True)),
                ('validated_secure_sql', models.TextField(blank=True, help_text='The safety-verified and normalized PostgreSQL string emitted by SQLGlot.', null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('processing', 'Processing'), ('blocked', 'Blocked by Guardrails'), ('failed', 'Execution Failure')], db_index=True, default='processing', max_length=20)),
                ('error_code', models.CharField(blank=True, help_text="A standardized error identifier (e.g., 'SQL_INJECTION_DETECTED', 'DB_TIMEOUT').", max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, help_text='A sanitized, safe descriptive string suitable for client-facing exposure.', null=True)),
                ('row_count', models.PositiveIntegerField(default=0, help_text='The absolute number of rows retrieved by the secure executor data cursor.')),
                ('latency_ms', models.PositiveIntegerField(default=0, help_text='Total execution turnaround time profiled in milliseconds.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'query_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
